#### Written by: Yousuf Shah
#### Subject: Numpy Tips And Trics
#### Date: 06.22.2024
#### Email: contact.ys09@gmail.com

# Numpy
---

In [25]:
# Import libraries
import numpy as np
import pandas as pd

# Create a 1D array

In [26]:
a=np.arange(9)
print(a.shape)
print(a)

(9,)
[0 1 2 3 4 5 6 7 8]


# create a 2D array 

In [27]:
b=a[np.newaxis, :]
print(b)
print(b.shape)
# change shape
b=a[: ,np.newaxis]
print(b)
b.shape


[[0 1 2 3 4 5 6 7 8]]
(1, 9)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


(9, 1)

In [28]:
# 2D Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Access element at row 1, column 2 (second element in the second row)
element_2d = arr_2d[1, 2]  # element_2d will be 6
element_2d
# print(arr_2d)
# arr_2d.shape

np.int64(6)

# Create a 3D Array

In [29]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Access element at depth 0, row 1, column 0 (first element in the second row of the first "slice")
element_3d = arr_3d[1, 0, 1]  # element_3d will be 5
# arr_3d.shape
print(arr_3d.shape)
arr_3d


(2, 2, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Create a Zero Array


In [30]:
zero_array=np.zeros((1,2,4))
zero_array


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Create a One Array


In [31]:
one_array=np.ones((3,2,4))
one_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# Create a Full Array

In [32]:
full_array=np.full((2,3,4), 5)
full_array

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

# Create a Identity Matrix

In [33]:
identity_matrix=np.eye(7)
identity_matrix

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

# Make an empty array near to zero values

In [34]:
np.empty((2,3)) # Matrix

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

# Create a Specific Array

In [35]:
# make an specific array 3 is starting number 4 is increament 20 is where we end the number
np.arange(3,20,4)

array([ 3,  7, 11, 15, 19])

In [36]:
# make even numbers
np.arange(0,25,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [37]:
# make odd numbers
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# Set Linear Trend 

In [38]:
# set linear trend between numbers 
lin=np.linspace(0, 10, num=11)
print(lin)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# Convert Float Array To Int Dtype Array

In [39]:
# Convert array float to int dtype
float_dtype=np.ones(2)
print(f'float dtype {float_dtype}')
print('----------------------------')
change_into_int_dtype=np.ones(2, dtype=np.int64)
print(f'Convert into int dtype {change_into_int_dtype}')

float dtype [1. 1.]
----------------------------
Convert into int dtype [1 1]


# Sorting array

In [40]:
arr=np.array([1,2,3,4,5,6,7,2,234,5,4,3])
print(np.sort(arr))

[  1   2   2   3   3   4   4   5   5   6   7 234]


# Concatenate Array

In [41]:
x=np.array([[1, 2], [3, 4]]) # 2X2 array
y=np.array([[5, 6], [7, 8]]) # 2X2 array

In [42]:
# concatenate 2D array
z=np.concatenate((x,y), axis=1) # if we use axis=1 than shape of arrays must be same 
print(z)

[[1 2 5 6]
 [3 4 7 8]]


# Reshape array

In [43]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                        
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [44]:
# check shape
array_example.shape

(3, 2, 4)

In [45]:
# reshpae 3D array size of the arrays must be same
reshaped=array_example.reshape(3,4,2)

In [46]:
# check shape
reshaped.shape

(3, 4, 2)

In [47]:
# check result
print(reshaped)

[[[0 1]
  [2 3]
  [4 5]
  [6 7]]

 [[0 1]
  [2 3]
  [4 5]
  [6 7]]

 [[0 1]
  [2 3]
  [4 5]
  [6 7]]]
